@startuml
hide circle
skinparam classAttributeIconSize 0

class "<<interface>>\nParser" as Parser
class SortCommandParser {
  +parse(args): SortCommand
}
class ParseException

class SortCommand {
  +COMMAND_WORD: String
}

SortCommandParser .up.|> Parser
Parser .right.> ParseException: throws >
SortCommandParser .right.> ParseException: throws >
@enduml
